In [1]:
import numpy as np

In [2]:
mylist = [1, 2, 3]

In [4]:
type(mylist)

list

In [5]:
np.array(mylist)
mylist

array([1, 2, 3])

In [12]:
myarr = np.array(mylist)
myarr

In [10]:
type(myarr)

numpy.ndarray

In [13]:
type(myarr)

numpy.ndarray

In [14]:
my_matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
my_matrix

In [16]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
np.arange(0, 101, 20)

array([  0,  20,  40,  60,  80, 100])

In [25]:
np.zeros((2, 5))  # Первое число - это количество строк, а второе число это количество колонок

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [33]:
np.ones((5))

array([1., 1., 1., 1., 1.])

In [41]:
lns = np.linspace(0, 5, 21)  # Получить равноотстающие числа в диапазоне, третье значение - это количество чисел(ВКЛЮЧИТЕЛЬНО)
len(lns)

In [45]:
np.eye(5)  # На главной диагонали 1, остальные 0

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [57]:
np.random.rand(5, 2)

array([[0.81601055, 0.50891998],
       [0.02498818, 0.05056117],
       [0.18962478, 0.23932977],
       [0.89258454, 0.97573694],
       [0.03746783, 0.73479928]])

In [60]:
np.random.randn(2, 3)  # Чем ближе числа к нулю тем больше вероятность получить их

array([[0.50754583, 1.28566612, 0.94490763],
       [1.46562291, 1.69332459, 1.09884647]])

In [71]:
np.random.randint(0, 101, (4, 5))

array([[65, 67, 21, 33, 10],
       [ 0, 15, 88, 32, 81],
       [34, 67, 19, 78, 59],
       [50, 14, 70,  3, 17]])

In [82]:
np.random.seed(101)  # Воспроизводимый набор чисел (главное чтобы число было одним и тем же когда мы хотим воспроизвести результат)
np.random.rand(4)  # Фиксированые результаты

array([0.51639863, 0.57066759, 0.02847423, 0.17152166])

In [84]:
np.random.rand(4)  # Разные результаты

array([0.72154386, 0.18993895, 0.55422759, 0.35213195])

In [85]:
arr = np.arange(0, 25)
arr

In [87]:
arr.reshape(5, 5)  # Форматирование в матрицу 5х5, должны уместиться все елементы массива

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [88]:
ranarr = np.random.randint(0, 101, 10)
ranarr

In [90]:
ranarr.max()

83

In [91]:
ranarr.min()

8

In [92]:
ranarr.argmax()  # Индекс максимального

1

In [94]:
ranarr.argmin()  # Индекс минимального

2

In [96]:
ranarr.dtype  # Тип данных в массиве

dtype('int64')

In [98]:
arr.shape  # Это не метод, а атрибут

(25,)

In [101]:
arr = arr.reshape(5, 5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [102]:
arr.shape

(5, 5)

In [104]:
arr.reshape(1, 25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])