In [1]:
import numpy as np

In [14]:
arr = np.arange(0, 11)
print(arr)
print(arr[8])
print(arr[1:5])  # До невключительного индекса
print(arr[7:])

[ 0  1  2  3  4  5  6  7  8  9 10]
8
[1 2 3 4]
[ 7  8  9 10]


In [15]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
arr[:5] = 100  # (Broadcasting) Для обычных списков это бы не сработало
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [22]:
arr = np.arange(0, 11)

In [31]:
slice_of_array = arr[0:5]  # Ссылка на элементы исходного массива
slice_of_array

array([99, 99, 99, 99, 99])

In [32]:
slice_of_array[:] = 99  # Присвоить всем елементам это значение

In [33]:
slice_of_array

array([99, 99, 99, 99, 99])

In [30]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [34]:
arr_copy = arr.copy()

In [36]:
arr_copy[:] = 100

In [37]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [38]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [40]:
arr_2d = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])

In [41]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [44]:
arr_2d.shape

(3, 3)

In [50]:
print(arr_2d[0])
print(arr_2d[2])

[ 5 10 15]
[35 40 45]


In [55]:
print(arr_2d[1][1])
print(arr_2d[1, 1])
print(arr_2d[0, 2])

25
25
15


In [58]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [59]:
print(arr_2d[:2, 1:])

[[10 15]
 [25 30]]


In [60]:
# Conditional Selection / Conditional Filtering

In [62]:
arr = np.arange(1, 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [63]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [64]:
bool_array = arr > 4

In [66]:
arr[bool_array]  # Числа больше 4

array([ 5,  6,  7,  8,  9, 10])

In [67]:
arr[arr>4]  # То же самое в одной строке

array([ 5,  6,  7,  8,  9, 10])